Segmentation: binary

Model:
  name: ReFineNet4Ch
  param:
    backbone: resnet50
    input_channels: 4

Criterion:
  name: Dice
  dice_weights: 1.0

Loader:
  root: data/s2_osm_4ch_sr/building_patches
  image_normalizer: divide_by_255
  label_normalizer: binary_label
  augmenters:
    - horizontal_flip
    - vertical_flip
    - rotation: 15
  batch_size: 4

Metrics:
  - accuracy
  - precision
  - f1
  - recall
  - iou

Optimizer:
  name: AdamW
  param:
    lr: 1e-4

Callbacks:
  log_dir: logs
  callers:
    - TimeCallback
    - TrainStateCallback
    - TrainChkCallback

